spring:
  profiles:
    active: dev

---
#local profile
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

---
#dev profile
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://learningchain.cnivwq0fnmgs.ap-northeast-2.rds.amazonaws.com/LC
    username: admin
    password: "!!LearningChain678"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace
---
#prod profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace
